package exception_handling_example1;

public class unproper_sequence_example 
{
	public static void main(String[] args)
	{
		/*// TODO Auto-generated method stub
		try
		{
			int a = 10/0;
		}
		catch(Exception e)
		{
			System.out.println("catch block of exception e");
		}
		
		catch(ArithmeticException e)
		{
			System.out.println("catch block of arithmetic exception e");
		}
		
		catch(RuntimeException e)
		{
			System.out.println("catch block of runtime exception e");
		}
		
		catch(throwable)
		{
			System.out.println("catch block of throwable");
		}  */
	  }
	}
